.TH sandbox "" "2013/07/02" "(1)"
.SH Name
.PP
sandbox - a project management tool
.SH SYNOPSIS
.PP
sandbox [\f[I]project\f[]]
.SH Description
.PP
sandbox is a project management tool based loosely on virtualenvwrapper.
It puts all your project directories together in one place and provides
a convenient way to jump straight into them from anywhere on the command
line.
.PP
The sandbox command itself serves as the jump command, while
\f[I]mksandbox\f[](1) and \f[I]rmsandbox\f[](1) are sumplemental
commands that allow you to create and destroy sandboxes.
\f[I]sandbox-config\f[](1) allows you to store environment variables
outside your project that autoload when entering the sandbox.
.PP
If \f[I]project\f[] isn\[aq]t provided, sandbox will return a list of
available sandboxes.
If the provided \f[I]project\f[] does not exist, sandbox will return an
error code of 1.
.SH SEE ALSO
.PP
\f[C]mksandbox\f[] (1), \f[C]rmsandbox\f[] (1), \f[C]sandbox-config\f[]
(1)
.SH AUTHORS
Anthony Ford.
