alias ls='ls -h '
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias chrome='google-chrome'

# Dotfile section walking
for dir in `ls $DOTFILES_HOME`
do
    if [[ -d $DOTFILES_HOME/$dir && ! $dir = "bash" && ! $dir = "bin" ]]
    then
        for file in `ls $DOTFILES_HOME/$dir/`
        do
            if [ ${file:(-6)} = ".alias" ]
            then
                source $DOTFILES_HOME/$dir/$file
            fi
        done
    fi
done
